#!/usr/bin/env bash
nmcli con show --active | tee screen.log
if
  grep -w "30a8a6b3-683b-4fd5-94c1-d155f1841120" screen.log
then
  echo "WIFI is enabled"
elif
  ping -c1 google.com >/dev/null
then
  notify-send "WIFI connected"
  nmcli device disconnect 28:C7:09:9D:C8:5E
  declare -i DEFAULT_TIMEOUT=9
  declare -i DEFAULT_INTERVAL=1
  declare -i DEFAULT_DELAY=1
  sleep 10
else
  notify-send "Enabling WIFI"
  nmcli radio wifi on
  nmcli device disconnect 28:C7:09:9D:C8:5E
  echo "Please wait"
  sleep 7
fi

if
  ping -c1 google.com >/dev/null
then
  Notify-send "WIFI Enabled successfully"
  nmcli device disconnect 28:C7:09:9D:C8:5E
  declare -i DEFAULT_TIMEOUT=9
  declare -i DEFAULT_INTERVAL=1
  declare -i DEFAULT_DELAY=1
  sleep 20
else
  bluetoothctl connect 28:C7:09:9D:C8:5E
  notify-send "No WIFI available - Enabling Hotspot"
  nmcli radio wifi off
  nmcli device connect 28:C7:09:9D:C8:5E
  sleep 3
fi
if
  ping -c1 google.com >/dev/null
then
  notify-send "Connection successful"
else
  notify-send "No connections are available - bluetooth may be disabled"
  nmcli device disconnect 28:C7:09:9D:C8:5E
fi
